name: FracturedSpawners
main: xyz.tangledwires.fracturedspawners.FracturedSpawners
version: 0
api-version: 1.21
author: xWires
commands:
  fracturedspawners:
    description: Manage FracturedSpawners
    usage: /fracturedspawners <reload>
    permission: fracturedspawners.admin